@startuml

title Base Class Concept.

' extends <|--
' implement <|..

interface OriginInterface {
    +void printSelf();
    +void printHello();
}

abstract class Origin {
    +void printHello();
}

class AA {
    +void printSelf();
    +void printHello();
}

class BB {
    +void printSelf();
    +void printHello();
}

class CC {
    +void printSelf();
    +void printHello();
}

class HH {
    +void printSelf();
}


' https://pdai.tech/md/java/basic/java-basic-oop.html
' 了解 Aggregation, Composition, Association, Dependency

OriginInterface <|.. Origin
Origin <|-- AA
Origin <|-- HH
AA <|-- BB
AA <|-- CC

@enduml
  